config/routes.rb
Todo::Application.routes.draw do
  resources :users, only: [:new, :create, :destroy, :edit]
  resources :sessions, only: [:new, :create, :destroy]
  root to: 'static_pages#home'
  match '/signup', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'

  

end

app/models/item.rb
class Item
  include Mongoid::Document

  field :name, type: String
  field :content, type: String
  field :priority, type: Integer

  validates_numericality_of :priority, 
  		greater_than_or_equal_to: 1,
  		less_than_or_equal_to: 5,
  		only_integer: true

  belongs_to :user, dependent: :delete
  has_and_belongs_to_many :tags

end

app/models/tag.rb
class Tag
  include Mongoid::Document

  field :name

  belongs_to :user, dependent: :delete
  has_and_belongs_to_many :items, index: true

end

app/models/user.rb
class User
  include Mongoid::Document
  include ActiveModel::SecurePassword

  field :email, type: String
  field :password_digest
  field :remember_token, type: String

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates_presence_of :email
  validates_uniqueness_of :email
  validates_format_of :email, with: VALID_EMAIL_REGEX
  validates_length_of :password, minimum: 8, maximum: 16
  validates_confirmation_of :password
  #validates :email, presence: true, uniqueness: true,
   #                 format: { with: VALID_EMAIL_REGEX}
  #validates :password, length: { minimum: 8, maximum: 16 },
   #                    confirmation: true


  before_save { self.email = email.downcase }
  before_create :generate_remember_token
  has_secure_password


  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

  def generate_remember_token
    self.remember_token = User.encrypt(User.new_remember_token)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/item_controller.rb
class ItemController < ApplicationController
	def new
		@item = Item.new
	end

	def create

	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
	end

	def create
		user = User.find_by(email: params[:session][:email].downcase)
		if user && user.authenticate(params[:session][:password])
			sign_in user
			redirect_to root_path
		else
			flash.now[:error] = 'Invalid email/password combination'
			render 'new'
		end
	end

	def destroy
		sign_out
		redirect_to root_path
	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      sign_in @user
      flash[:success] = "Success!"
      redirect_to root_path
    else
      render 'new'
    end
  end

  def edit

  end

  def destroy 

  end

  private 

	def user_params
		params.require(:user).permit(:email, :password, 
									 :password_confirmation)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/item_helper.rb
module ItemHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

	def signed_in?
		!current_user.nil?
	end

	def sign_in(user)
		remember_token = User.new_remember_token
		cookies.permanent[:remember_token] = remember_token
		user.update_attribute(:remember_token, User.encrypt(remember_token))
		self.current_user = user
	end

	def signed_in?
		!current_user.nil?
	end

	def sign_out
		self.current_user = nil
		cookies.delete(:remember_token)
	end

	def current_user=(user)
		@current_user = user
	end

	def current_user
    	remember_token = User.encrypt(cookies[:remember_token])
    	@current_user ||= User.find_by(remember_token: remember_token)
  	end

	def current_user?(user)
		user == current_user
	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <p>Created by Michael Allen </p>
  </small>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "#todo", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <% if signed_in? %>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <%= current_user.email %> <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li> 
                  <%= link_to "Sign out", signout_path, method: 'delete' %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_home_signedin.html.erb
<div id="feed" class="col-lg-6 col-lg-offset-3">
	<h1>Signed in bitch </h1>
</div>

app/views/layouts/_home_unsigned.html.erb
<div class="center hero-unit">
	<h1>todo: finish this website</h1>

	<h2>
		Keep track of your shit with #todo
	</h2>

	<%= link_to "Create an Account", signup_path, class: "btn btn-large btn-primary", id: "sign_up"%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Todo</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render 'layouts/header' %><div class="container">
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>"><%= value %></div>
    <% end %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </div>
</body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/home.html.erb
<% if signed_in? %>
	<%= render 'layouts/home_signedin' %>
<% else %>
	<%=	 render 'layouts/home_unsigned' %>
<% end %>

app/views/users/_fields.html.erb
<%= render 'shared/error_messages', object: f.object %>

<%= f.label :email %>
<%= f.text_field :email %>	

<%= f.label :password %>
<%= f.password_field :password %>

<%= f.label :password_confirmation, "Confirm Password" %>
<%= f.password_field :password_confirmation %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>

<div class="row">
    <div class="span6 offset3">
		<h5>Create your account</h5>
  		<%= form_for(@user) do |f| %>
  			<%= render 'fields', f: f %>
      		<%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    	<% end %>
    </div>
</div>